// deck.js — seed deck. Nouns chosen so der/die/das are well mixed and include
// the classic "gotcha" pairs (das Mädchen, der Mond vs die Sonne).
// gender: "der" | "die" | "das". `noun` is the bare word; the article is the
// thing you're being tested on, so it's never shown on the front.

export const SEED = [
  { noun: "Mann", gender: "der", plural: "Männer", nominative: "der Mann", genitive: "des Mannes", dative: "dem Mann", accusative: "den Mann", en: "man" },
  { noun: "Frau", gender: "die", plural: "Frauen", nominative: "die Frau", genitive: "der Frau", dative: "der Frau", accusative: "die Frau", en: "woman" },
  { noun: "Kind", gender: "das", plural: "Kinder", nominative: "das Kind", genitive: "des Kindes", dative: "dem Kind", accusative: "das Kind", en: "child" },
  { noun: "Junge", gender: "der", plural: "Jungen", nominative: "der Junge", genitive: "des Jungen", dative: "dem Jungen", accusative: "den Jungen", en: "boy" },
  { noun: "Mädchen", gender: "das", plural: "Mädchen", nominative: "das Mädchen", genitive: "des Mädchens", dative: "dem Mädchen", accusative: "das Mädchen", en: "girl" },
  { noun: "Tisch", gender: "der", plural: "Tische", nominative: "der Tisch", genitive: "des Tisches", dative: "dem Tisch", accusative: "den Tisch", en: "table" },
  { noun: "Stuhl", gender: "der", plural: "Stühle", nominative: "der Stuhl", genitive: "des Stuhles", dative: "dem Stuhl", accusative: "den Stuhl", en: "chair" },
  { noun: "Bett", gender: "das", plural: "Betten", nominative: "das Bett", genitive: "des Bettes", dative: "dem Bett", accusative: "das Bett", en: "bed" },
  { noun: "Tür", gender: "die", plural: "Türen", nominative: "die Tür", genitive: "der Tür", dative: "der Tür", accusative: "die Tür", en: "door" },
  { noun: "Fenster", gender: "das", plural: "Fenster", nominative: "das Fenster", genitive: "des Fensters", dative: "dem Fenster", accusative: "das Fenster", en: "window" },
  { noun: "Haus", gender: "das", plural: "Häuser", nominative: "das Haus", genitive: "des Hauses", dative: "dem Haus", accusative: "das Haus", en: "house" },
  { noun: "Hund", gender: "der", plural: "Hunde", nominative: "der Hund", genitive: "des Hundes", dative: "dem Hund", accusative: "den Hund", en: "dog" },
  { noun: "Katze", gender: "die", plural: "Katzen", nominative: "die Katze", genitive: "der Katze", dative: "der Katze", accusative: "die Katze", en: "cat" },
  { noun: "Pferd", gender: "das", plural: "Pferde", nominative: "das Pferd", genitive: "des Pferdes", dative: "dem Pferd", accusative: "das Pferd", en: "horse" },
  { noun: "Apfel", gender: "der", plural: "Äpfel", nominative: "der Apfel", genitive: "des Apfels", dative: "dem Apfel", accusative: "den Apfel", en: "apple" },
  { noun: "Banane", gender: "die", plural: "Bananen", nominative: "die Banane", genitive: "der Banane", dative: "der Banane", accusative: "die Banane", en: "banana" },
  { noun: "Brot", gender: "das", plural: "Brote", nominative: "das Brot", genitive: "des Brotes", dative: "dem Brot", accusative: "das Brot", en: "bread" },
  { noun: "Wasser", gender: "das", plural: "Wässer", nominative: "das Wasser", genitive: "des Wassers", dative: "dem Wasser", accusative: "das Wasser", en: "water" },
  { noun: "Kaffee", gender: "der", plural: "Kaffees", nominative: "der Kaffee", genitive: "des Kaffees", dative: "dem Kaffee", accusative: "den Kaffee", en: "coffee" },
  { noun: "Milch", gender: "die", plural: "—", nominative: "die Milch", genitive: "der Milch", dative: "der Milch", accusative: "die Milch", en: "milk" },
  { noun: "Tee", gender: "der", plural: "Tees", nominative: "der Tee", genitive: "des Tees", dative: "dem Tee", accusative: "den Tee", en: "tea" },
  { noun: "Bier", gender: "das", plural: "Biere", nominative: "das Bier", genitive: "des Bieres", dative: "dem Bier", accusative: "das Bier", en: "beer" },
  { noun: "Wein", gender: "der", plural: "Weine", nominative: "der Wein", genitive: "des Weines", dative: "dem Wein", accusative: "den Wein", en: "wine" },
  { noun: "Suppe", gender: "die", plural: "Suppen", nominative: "die Suppe", genitive: "der Suppe", dative: "der Suppe", accusative: "die Suppe", en: "soup" },
  { noun: "Tag", gender: "der", plural: "Tage", nominative: "der Tag", genitive: "des Tages", dative: "dem Tag", accusative: "den Tag", en: "day" },
  { noun: "Nacht", gender: "die", plural: "Nächte", nominative: "die Nacht", genitive: "der Nacht", dative: "der Nacht", accusative: "die Nacht", en: "night" },
  { noun: "Woche", gender: "die", plural: "Wochen", nominative: "die Woche", genitive: "der Woche", dative: "der Woche", accusative: "die Woche", en: "week" },
  { noun: "Monat", gender: "der", plural: "Monate", nominative: "der Monat", genitive: "des Monats", dative: "dem Monat", accusative: "den Monat", en: "month" },
  { noun: "Jahr", gender: "das", plural: "Jahre", nominative: "das Jahr", genitive: "des Jahres", dative: "dem Jahr", accusative: "das Jahr", en: "year" },
  { noun: "Zeit", gender: "die", plural: "Zeiten", nominative: "die Zeit", genitive: "der Zeit", dative: "der Zeit", accusative: "die Zeit", en: "time" },
  { noun: "Sonne", gender: "die", plural: "Sonnen", nominative: "die Sonne", genitive: "der Sonne", dative: "der Sonne", accusative: "die Sonne", en: "sun" },
  { noun: "Mond", gender: "der", plural: "Monde", nominative: "der Mond", genitive: "des Mondes", dative: "dem Mond", accusative: "den Mond", en: "moon" },
  { noun: "Stern", gender: "der", plural: "Sterne", nominative: "der Stern", genitive: "des Sternes", dative: "dem Stern", accusative: "den Stern", en: "star" },
  { noun: "Himmel", gender: "der", plural: "Himmel", nominative: "der Himmel", genitive: "des Himmels", dative: "dem Himmel", accusative: "den Himmel", en: "sky" },
  { noun: "Regen", gender: "der", plural: "—", nominative: "der Regen", genitive: "des Regens", dative: "dem Regen", accusative: "den Regen", en: "rain" },
  { noun: "Schnee", gender: "der", plural: "—", nominative: "der Schnee", genitive: "des Schnees", dative: "dem Schnee", accusative: "den Schnee", en: "snow" },
  { noun: "Wind", gender: "der", plural: "Winde", nominative: "der Wind", genitive: "des Windes", dative: "dem Wind", accusative: "den Wind", en: "wind" },
  { noun: "Wolke", gender: "die", plural: "Wolken", nominative: "die Wolke", genitive: "der Wolke", dative: "der Wolke", accusative: "die Wolke", en: "cloud" },
  { noun: "Auto", gender: "das", plural: "Autos", nominative: "das Auto", genitive: "des Autos", dative: "dem Auto", accusative: "das Auto", en: "car" },
  { noun: "Zug", gender: "der", plural: "Züge", nominative: "der Zug", genitive: "des Zuges", dative: "dem Zug", accusative: "den Zug", en: "train" },
  { noun: "Fahrrad", gender: "das", plural: "Fahrräder", nominative: "das Fahrrad", genitive: "des Fahrrades", dative: "dem Fahrrad", accusative: "das Fahrrad", en: "bicycle" },
  { noun: "Flugzeug", gender: "das", plural: "Flugzeuge", nominative: "das Flugzeug", genitive: "des Flugzeuges", dative: "dem Flugzeug", accusative: "das Flugzeug", en: "airplane" },
  { noun: "Stadt", gender: "die", plural: "Städte", nominative: "die Stadt", genitive: "der Stadt", dative: "der Stadt", accusative: "die Stadt", en: "city" },
  { noun: "Land", gender: "das", plural: "Länder", nominative: "das Land", genitive: "des Landes", dative: "dem Land", accusative: "das Land", en: "country" },
  { noun: "Straße", gender: "die", plural: "Straßen", nominative: "die Straße", genitive: "der Straße", dative: "der Straße", accusative: "die Straße", en: "street" },
  { noun: "Weg", gender: "der", plural: "Wege", nominative: "der Weg", genitive: "des Weges", dative: "dem Weg", accusative: "den Weg", en: "way / path" },
  { noun: "Freund", gender: "der", plural: "Freunde", nominative: "der Freund", genitive: "des Freundes", dative: "dem Freund", accusative: "den Freund", en: "friend (m)" },
  { noun: "Familie", gender: "die", plural: "Familien", nominative: "die Familie", genitive: "der Familie", dative: "der Familie", accusative: "die Familie", en: "family" },
  { noun: "Liebe", gender: "die", plural: "—", nominative: "die Liebe", genitive: "der Liebe", dative: "der Liebe", accusative: "die Liebe", en: "love" },
  { noun: "Hand", gender: "die", plural: "Hände", nominative: "die Hand", genitive: "der Hand", dative: "der Hand", accusative: "die Hand", en: "hand" },
  { noun: "Kopf", gender: "der", plural: "Köpfe", nominative: "der Kopf", genitive: "des Kopfes", dative: "dem Kopf", accusative: "den Kopf", en: "head" },
  { noun: "Auge", gender: "das", plural: "Augen", nominative: "das Auge", genitive: "des Auges", dative: "dem Auge", accusative: "das Auge", en: "eye" },
  { noun: "Ohr", gender: "das", plural: "Ohren", nominative: "das Ohr", genitive: "des Ohres", dative: "dem Ohr", accusative: "das Ohr", en: "ear" },
  { noun: "Fuß", gender: "der", plural: "Füße", nominative: "der Fuß", genitive: "des Fußes", dative: "dem Fuß", accusative: "den Fuß", en: "foot" },
  { noun: "Herz", gender: "das", plural: "Herzen", nominative: "das Herz", genitive: "des Herzens", dative: "dem Herzen", accusative: "das Herz", en: "heart" },
  { noun: "Name", gender: "der", plural: "Namen", nominative: "der Name", genitive: "des Namens", dative: "dem Namen", accusative: "den Namen", en: "name" },
  { noun: "Geld", gender: "das", plural: "Gelder", nominative: "das Geld", genitive: "des Geldes", dative: "dem Geld", accusative: "das Geld", en: "money" },
  { noun: "Arbeit", gender: "die", plural: "Arbeiten", nominative: "die Arbeit", genitive: "der Arbeit", dative: "der Arbeit", accusative: "die Arbeit", en: "work" },
  { noun: "Lehrer", gender: "der", plural: "Lehrer", nominative: "der Lehrer", genitive: "des Lehrers", dative: "dem Lehrer", accusative: "den Lehrer", en: "teacher (m)" },
  { noun: "Schule", gender: "die", plural: "Schulen", nominative: "die Schule", genitive: "der Schule", dative: "der Schule", accusative: "die Schule", en: "school" },
  { noun: "Buch", gender: "das", plural: "Bücher", nominative: "das Buch", genitive: "des Buches", dative: "dem Buch", accusative: "das Buch", en: "book" },
  { noun: "Wort", gender: "das", plural: "Wörter", nominative: "das Wort", genitive: "des Wortes", dative: "dem Wort", accusative: "das Wort", en: "word" },
  { noun: "Sprache", gender: "die", plural: "Sprachen", nominative: "die Sprache", genitive: "der Sprache", dative: "der Sprache", accusative: "die Sprache", en: "language" },
  { noun: "Frage", gender: "die", plural: "Fragen", nominative: "die Frage", genitive: "der Frage", dative: "der Frage", accusative: "die Frage", en: "question" },
  { noun: "Antwort", gender: "die", plural: "Antworten", nominative: "die Antwort", genitive: "der Antwort", dative: "der Antwort", accusative: "die Antwort", en: "answer" },
  { noun: "Garten", gender: "der", plural: "Gärten", nominative: "der Garten", genitive: "des Gartens", dative: "dem Garten", accusative: "den Garten", en: "garden" },
  { noun: "Baum", gender: "der", plural: "Bäume", nominative: "der Baum", genitive: "des Baumes", dative: "dem Baum", accusative: "den Baum", en: "tree" },
  { noun: "Blume", gender: "die", plural: "Blumen", nominative: "die Blume", genitive: "der Blume", dative: "der Blume", accusative: "die Blume", en: "flower" },
  { noun: "Morgen", gender: "der", plural: "Morgen", nominative: "der Morgen", genitive: "des Morgens", dative: "dem Morgen", accusative: "den Morgen", en: "morning" },
  { noun: "Abend", gender: "der", plural: "Abende", nominative: "der Abend", genitive: "des Abends", dative: "dem Abend", accusative: "den Abend", en: "evening" },
  { noun: "Minute", gender: "die", plural: "Minuten", nominative: "die Minute", genitive: "der Minute", dative: "der Minute", accusative: "die Minute", en: "minute" },
  { noun: "Stunde", gender: "die", plural: "Stunden", nominative: "die Stunde", genitive: "der Stunde", dative: "der Stunde", accusative: "die Stunde", en: "hour" },
  { noun: "Geburtstag", gender: "der", plural: "Geburtstage", nominative: "der Geburtstag", genitive: "des Geburtstags", dative: "dem Geburtstag", accusative: "den Geburtstag", en: "birthday" },
  { noun: "Urlaub", gender: "der", plural: "Urlaube", nominative: "der Urlaub", genitive: "des Urlaubs", dative: "dem Urlaub", accusative: "den Urlaub", en: "vacation" },
  { noun: "Wetter", gender: "das", plural: "—", nominative: "das Wetter", genitive: "des Wetters", dative: "dem Wetter", accusative: "das Wetter", en: "weather" },
  { noun: "Feuer", gender: "das", plural: "—", nominative: "das Feuer", genitive: "des Feuers", dative: "dem Feuer", accusative: "das Feuer", en: "fire" },
  { noun: "Luft", gender: "die", plural: "—", nominative: "die Luft", genitive: "der Luft", dative: "der Luft", accusative: "die Luft", en: "air" },
  { noun: "Erde", gender: "die", plural: "Erden", nominative: "die Erde", genitive: "der Erde", dative: "der Erde", accusative: "die Erde", en: "earth / ground" },
  { noun: "Wohnung", gender: "die", plural: "Wohnungen", nominative: "die Wohnung", genitive: "der Wohnung", dative: "der Wohnung", accusative: "die Wohnung", en: "apartment" },
  { noun: "Decke", gender: "die", plural: "Decken", nominative: "die Decke", genitive: "der Decke", dative: "der Decke", accusative: "die Decke", en: "ceiling / blanket" },
  { noun: "Wand", gender: "die", plural: "Wände", nominative: "die Wand", genitive: "der Wand", dative: "der Wand", accusative: "die Wand", en: "wall" },
  { noun: "Boden", gender: "der", plural: "Böden", nominative: "der Boden", genitive: "des Bodens", dative: "dem Boden", accusative: "den Boden", en: "floor / ground" },
  { noun: "Dach", gender: "das", plural: "Dächer", nominative: "das Dach", genitive: "des Daches", dative: "dem Dach", accusative: "das Dach", en: "roof" },
  { noun: "Treppe", gender: "die", plural: "Treppen", nominative: "die Treppe", genitive: "der Treppe", dative: "der Treppe", accusative: "die Treppe", en: "staircase" },
  { noun: "Schlüssel", gender: "der", plural: "Schlüssel", nominative: "der Schlüssel", genitive: "des Schlüssels", dative: "dem Schlüssel", accusative: "den Schlüssel", en: "key" },
  { noun: "Tasche", gender: "die", plural: "Taschen", nominative: "die Tasche", genitive: "der Tasche", dative: "der Tasche", accusative: "die Tasche", en: "bag / pocket" },
  { noun: "Koffer", gender: "der", plural: "Koffer", nominative: "der Koffer", genitive: "des Koffers", dative: "dem Koffer", accusative: "den Koffer", en: "suitcase" },
  { noun: "Geschenk", gender: "das", plural: "Geschenke", nominative: "das Geschenk", genitive: "des Geschenks", dative: "dem Geschenk", accusative: "das Geschenk", en: "gift" },
  { noun: "Zeitung", gender: "die", plural: "Zeitungen", nominative: "die Zeitung", genitive: "der Zeitung", dative: "der Zeitung", accusative: "die Zeitung", en: "newspaper" },
  { noun: "Nachricht", gender: "die", plural: "Nachrichten", nominative: "die Nachricht", genitive: "der Nachricht", dative: "der Nachricht", accusative: "die Nachricht", en: "message / news item" },
  { noun: "Nummer", gender: "die", plural: "Nummern", nominative: "die Nummer", genitive: "der Nummer", dative: "der Nummer", accusative: "die Nummer", en: "number" },
  { noun: "Adresse", gender: "die", plural: "Adressen", nominative: "die Adresse", genitive: "der Adresse", dative: "der Adresse", accusative: "die Adresse", en: "address" },
  { noun: "E-Mail", gender: "die", plural: "E-Mails", nominative: "die E-Mail", genitive: "der E-Mail", dative: "der E-Mail", accusative: "die E-Mail", en: "email" },
  { noun: "Internet", gender: "das", plural: "—", nominative: "das Internet", genitive: "des Internets", dative: "dem Internet", accusative: "das Internet", en: "internet" },
  { noun: "Bildschirm", gender: "der", plural: "Bildschirme", nominative: "der Bildschirm", genitive: "des Bildschirms", dative: "dem Bildschirm", accusative: "den Bildschirm", en: "screen / monitor" },
  { noun: "Maus", gender: "die", plural: "Mäuse", nominative: "die Maus", genitive: "der Maus", dative: "der Maus", accusative: "die Maus", en: "mouse" },
  { noun: "Taste", gender: "die", plural: "Tasten", nominative: "die Taste", genitive: "der Taste", dative: "der Taste", accusative: "die Taste", en: "key / button" },
  { noun: "Pause", gender: "die", plural: "Pausen", nominative: "die Pause", genitive: "der Pause", dative: "der Pause", accusative: "die Pause", en: "break" },
  { noun: "Termin", gender: "der", plural: "Termine", nominative: "der Termin", genitive: "des Termins", dative: "dem Termin", accusative: "den Termin", en: "appointment" },
  { noun: "Plan", gender: "der", plural: "Pläne", nominative: "der Plan", genitive: "des Plans", dative: "dem Plan", accusative: "den Plan", en: "plan" },
  { noun: "Problem", gender: "das", plural: "Probleme", nominative: "das Problem", genitive: "des Problems", dative: "dem Problem", accusative: "das Problem", en: "problem" },
  { noun: "Idee", gender: "die", plural: "Ideen", nominative: "die Idee", genitive: "der Idee", dative: "der Idee", accusative: "die Idee", en: "idea" },
  { noun: "Hilfe", gender: "die", plural: "—", nominative: "die Hilfe", genitive: "der Hilfe", dative: "der Hilfe", accusative: "die Hilfe", en: "help" },
  { noun: "Anfang", gender: "der", plural: "Anfänge", nominative: "der Anfang", genitive: "des Anfangs", dative: "dem Anfang", accusative: "den Anfang", en: "beginning" },
  { noun: "Ende", gender: "das", plural: "Enden", nominative: "das Ende", genitive: "des Endes", dative: "dem Ende", accusative: "das Ende", en: "end" },
  { noun: "Beispiel", gender: "das", plural: "Beispiele", nominative: "das Beispiel", genitive: "des Beispiels", dative: "dem Beispiel", accusative: "das Beispiel", en: "example" },
  { noun: "Fehler", gender: "der", plural: "Fehler", nominative: "der Fehler", genitive: "des Fehlers", dative: "dem Fehler", accusative: "den Fehler", en: "mistake / error" },
  { noun: "Grund", gender: "der", plural: "Gründe", nominative: "der Grund", genitive: "des Grundes", dative: "dem Grund", accusative: "den Grund", en: "reason / ground" },
  { noun: "Teil", gender: "der", plural: "Teile", nominative: "der Teil", genitive: "des Teils", dative: "dem Teil", accusative: "den Teil", en: "part" },
  { noun: "Seite", gender: "die", plural: "Seiten", nominative: "die Seite", genitive: "der Seite", dative: "der Seite", accusative: "die Seite", en: "side / page" },
  { noun: "Stelle", gender: "die", plural: "Stellen", nominative: "die Stelle", genitive: "der Stelle", dative: "der Stelle", accusative: "die Stelle", en: "place / position" },
  { noun: "Sache", gender: "die", plural: "Sachen", nominative: "die Sache", genitive: "der Sache", dative: "der Sache", accusative: "die Sache", en: "thing / matter" },
  { noun: "Welt", gender: "die", plural: "Welten", nominative: "die Welt", genitive: "der Welt", dative: "der Welt", accusative: "die Welt", en: "world" },
  { noun: "Geschichte", gender: "die", plural: "Geschichten", nominative: "die Geschichte", genitive: "der Geschichte", dative: "der Geschichte", accusative: "die Geschichte", en: "story / history" },
  { noun: "Dorf", gender: "das", plural: "Dörfer", nominative: "das Dorf", genitive: "des Dorfes", dative: "dem Dorf", accusative: "das Dorf", en: "village" },
  { noun: "Ort", gender: "der", plural: "Orte", nominative: "der Ort", genitive: "des Ortes", dative: "dem Ort", accusative: "den Ort", en: "place / location" },
  { noun: "Gegend", gender: "die", plural: "Gegenden", nominative: "die Gegend", genitive: "der Gegend", dative: "der Gegend", accusative: "die Gegend", en: "area / region" },
  { noun: "Grenze", gender: "die", plural: "Grenzen", nominative: "die Grenze", genitive: "der Grenze", dative: "der Grenze", accusative: "die Grenze", en: "border / limit" },
  { noun: "Gespräch", gender: "das", plural: "Gespräche", nominative: "das Gespräch", genitive: "des Gesprächs", dative: "dem Gespräch", accusative: "das Gespräch", en: "conversation" },
  { noun: "Stimme", gender: "die", plural: "Stimmen", nominative: "die Stimme", genitive: "der Stimme", dative: "der Stimme", accusative: "die Stimme", en: "voice" },
  { noun: "Geräusch", gender: "das", plural: "Geräusche", nominative: "das Geräusch", genitive: "des Geräusches", dative: "dem Geräusch", accusative: "das Geräusch", en: "sound / noise" },
  { noun: "Meinung", gender: "die", plural: "Meinungen", nominative: "die Meinung", genitive: "der Meinung", dative: "der Meinung", accusative: "die Meinung", en: "opinion" },
  { noun: "Wunsch", gender: "der", plural: "Wünsche", nominative: "der Wunsch", genitive: "des Wunsches", dative: "dem Wunsch", accusative: "den Wunsch", en: "wish" },
  { noun: "Hoffnung", gender: "die", plural: "—", nominative: "die Hoffnung", genitive: "der Hoffnung", dative: "der Hoffnung", accusative: "die Hoffnung", en: "hope" },
  { noun: "Angst", gender: "die", plural: "Ängste", nominative: "die Angst", genitive: "der Angst", dative: "der Angst", accusative: "die Angst", en: "fear" },
  { noun: "Freude", gender: "die", plural: "Freuden", nominative: "die Freude", genitive: "der Freude", dative: "der Freude", accusative: "die Freude", en: "joy" },
  { noun: "Spaß", gender: "der", plural: "Späße", nominative: "der Spaß", genitive: "des Spaßes", dative: "dem Spaß", accusative: "den Spaß", en: "fun / joke" },
  { noun: "Glück", gender: "das", plural: "—", nominative: "das Glück", genitive: "des Glücks", dative: "dem Glück", accusative: "das Glück", en: "luck / happiness" },
  { noun: "Pech", gender: "das", plural: "—", nominative: "das Pech", genitive: "des Pechs", dative: "dem Pech", accusative: "das Pech", en: "bad luck" },
  { noun: "Ruhe", gender: "die", plural: "—", nominative: "die Ruhe", genitive: "der Ruhe", dative: "der Ruhe", accusative: "die Ruhe", en: "quiet / rest" },
  { noun: "Gefahr", gender: "die", plural: "Gefahren", nominative: "die Gefahr", genitive: "der Gefahr", dative: "der Gefahr", accusative: "die Gefahr", en: "danger" },
  { noun: "Sicherheit", gender: "die", plural: "—", nominative: "die Sicherheit", genitive: "der Sicherheit", dative: "der Sicherheit", accusative: "die Sicherheit", en: "safety / security" },
  { noun: "Gesundheit", gender: "die", plural: "—", nominative: "die Gesundheit", genitive: "der Gesundheit", dative: "der Gesundheit", accusative: "die Gesundheit", en: "health" },
  { noun: "Hunger", gender: "der", plural: "—", nominative: "der Hunger", genitive: "des Hungers", dative: "dem Hunger", accusative: "den Hunger", en: "hunger" },
  { noun: "Durst", gender: "der", plural: "—", nominative: "der Durst", genitive: "des Durstes", dative: "dem Durst", accusative: "den Durst", en: "thirst" },
  { noun: "Frühstück", gender: "das", plural: "Frühstücke", nominative: "das Frühstück", genitive: "des Frühstücks", dative: "dem Frühstück", accusative: "das Frühstück", en: "breakfast" },
  { noun: "Mittagessen", gender: "das", plural: "Mittagessen", nominative: "das Mittagessen", genitive: "des Mittagessens", dative: "dem Mittagessen", accusative: "das Mittagessen", en: "lunch" },
  { noun: "Abendessen", gender: "das", plural: "Abendessen", nominative: "das Abendessen", genitive: "des Abendessens", dative: "dem Abendessen", accusative: "das Abendessen", en: "dinner" },
  { noun: "Gemüse", gender: "das", plural: "—", nominative: "das Gemüse", genitive: "des Gemüses", dative: "dem Gemüse", accusative: "das Gemüse", en: "vegetables" },
  { noun: "Kartoffel", gender: "die", plural: "Kartoffeln", nominative: "die Kartoffel", genitive: "der Kartoffel", dative: "der Kartoffel", accusative: "die Kartoffel", en: "potato" },
  { noun: "Tomate", gender: "die", plural: "Tomaten", nominative: "die Tomate", genitive: "der Tomate", dative: "der Tomate", accusative: "die Tomate", en: "tomato" },
  { noun: "Orange", gender: "die", plural: "Orangen", nominative: "die Orange", genitive: "der Orange", dative: "der Orange", accusative: "die Orange", en: "orange" },
  { noun: "Traube", gender: "die", plural: "Trauben", nominative: "die Traube", genitive: "der Traube", dative: "der Traube", accusative: "die Traube", en: "grape" },
  { noun: "Erdbeere", gender: "die", plural: "Erdbeeren", nominative: "die Erdbeere", genitive: "der Erdbeere", dative: "der Erdbeere", accusative: "die Erdbeere", en: "strawberry" },
  { noun: "Kuchen", gender: "der", plural: "Kuchen", nominative: "der Kuchen", genitive: "des Kuchens", dative: "dem Kuchen", accusative: "den Kuchen", en: "cake" },
  { noun: "Schokolade", gender: "die", plural: "Schokoladen", nominative: "die Schokolade", genitive: "der Schokolade", dative: "der Schokolade", accusative: "die Schokolade", en: "chocolate" },
  { noun: "Restaurant", gender: "das", plural: "Restaurants", nominative: "das Restaurant", genitive: "des Restaurants", dative: "dem Restaurant", accusative: "das Restaurant", en: "restaurant" },
  { noun: "Rechnung", gender: "die", plural: "Rechnungen", nominative: "die Rechnung", genitive: "der Rechnung", dative: "der Rechnung", accusative: "die Rechnung", en: "bill / invoice" },
  { noun: "Geschäft", gender: "das", plural: "Geschäfte", nominative: "das Geschäft", genitive: "des Geschäfts", dative: "dem Geschäft", accusative: "das Geschäft", en: "shop / business" },
  { noun: "Bank", gender: "die", plural: "Banken", nominative: "die Bank", genitive: "der Bank", dative: "der Bank", accusative: "die Bank", en: "bank" },
  { noun: "Postamt", gender: "das", plural: "Postämter", nominative: "das Postamt", genitive: "des Postamts", dative: "dem Postamt", accusative: "das Postamt", en: "post office" },
  { noun: "Apotheke", gender: "die", plural: "Apotheken", nominative: "die Apotheke", genitive: "der Apotheke", dative: "der Apotheke", accusative: "die Apotheke", en: "pharmacy" },
  { noun: "Bäckerei", gender: "die", plural: "Bäckereien", nominative: "die Bäckerei", genitive: "der Bäckerei", dative: "der Bäckerei", accusative: "die Bäckerei", en: "bakery" },
  { noun: "Metzgerei", gender: "die", plural: "Metzgereien", nominative: "die Metzgerei", genitive: "der Metzgerei", dative: "der Metzgerei", accusative: "die Metzgerei", en: "butcher shop" },
  { noun: "Kleid", gender: "das", plural: "Kleider", nominative: "das Kleid", genitive: "des Kleides", dative: "dem Kleid", accusative: "das Kleid", en: "dress" },
  { noun: "Pullover", gender: "der", plural: "Pullover", nominative: "der Pullover", genitive: "des Pullovers", dative: "dem Pullover", accusative: "den Pullover", en: "sweater" },
  { noun: "Gürtel", gender: "der", plural: "Gürtel", nominative: "der Gürtel", genitive: "des Gürtels", dative: "dem Gürtel", accusative: "den Gürtel", en: "belt" },
  { noun: "Mütze", gender: "die", plural: "Mützen", nominative: "die Mütze", genitive: "der Mütze", dative: "der Mütze", accusative: "die Mütze", en: "cap / beanie" },
  { noun: "Handschuh", gender: "der", plural: "Handschuhe", nominative: "der Handschuh", genitive: "des Handschuhs", dative: "dem Handschuh", accusative: "den Handschuh", en: "glove" },
  { noun: "Regenschirm", gender: "der", plural: "Regenschirme", nominative: "der Regenschirm", genitive: "des Regenschirms", dative: "dem Regenschirm", accusative: "den Regenschirm", en: "umbrella" },
  { noun: "Brille", gender: "die", plural: "Brillen", nominative: "die Brille", genitive: "der Brille", dative: "der Brille", accusative: "die Brille", en: "glasses" },
  { noun: "Ring", gender: "der", plural: "Ringe", nominative: "der Ring", genitive: "des Ringes", dative: "dem Ring", accusative: "den Ring", en: "ring" },
  { noun: "Kette", gender: "die", plural: "Ketten", nominative: "die Kette", genitive: "der Kette", dative: "der Kette", accusative: "die Kette", en: "chain / necklace" },
  { noun: "Kalender", gender: "der", plural: "Kalender", nominative: "der Kalender", genitive: "des Kalenders", dative: "dem Kalender", accusative: "den Kalender", en: "calendar" },
  { noun: "Einladung", gender: "die", plural: "Einladungen", nominative: "die Einladung", genitive: "der Einladung", dative: "der Einladung", accusative: "die Einladung", en: "invitation" },
  { noun: "Hochzeit", gender: "die", plural: "Hochzeiten", nominative: "die Hochzeit", genitive: "der Hochzeit", dative: "der Hochzeit", accusative: "die Hochzeit", en: "wedding" },
  { noun: "Eingang", gender: "der", plural: "Eingänge", nominative: "der Eingang", genitive: "des Eingangs", dative: "dem Eingang", accusative: "den Eingang", en: "entrance" },
  { noun: "Ausgang", gender: "der", plural: "Ausgänge", nominative: "der Ausgang", genitive: "des Ausgangs", dative: "dem Ausgang", accusative: "den Ausgang", en: "exit" },
];

// Deduplicate (the seed intentionally repeats "Mann" as a typo-guard demo of
// how the loader collapses dupes by noun+meaning).
export function loadSeed() {
  const seen = new Set();
  const out = [];
  for (const w of SEED) {
    const key = `${w.noun}::${w.en}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(w);
  }
  return out;
}
