// Version four expands Artikel independently of the grammar libraries.
// `casePracticeStatus: "pending"` is intentional: a noun is promoted to Fälle
// only after its morphology and examples have passed editorial review.
// Within each CEFR level, records are ordered from broader corpus usefulness
// toward more specialised vocabulary.
const RAW_NOUNS = [
  // A1–A2: high-utility gaps in daily life
  ["Alltag", "der", "everyday life", "A1"],
  ["Anfang", "der", "beginning", "A1"],
  ["Bäckerei", "die", "bakery", "A1"],
  ["Badezimmer", "das", "bathroom", "A1"],
  ["Bahnhof", "der", "train station", "A1"],
  ["Balkon", "der", "balcony", "A1"],
  ["Banane", "die", "banana", "A1"],
  ["Bleistift", "der", "pencil", "A1"],
  ["Brille", "die", "glasses", "A1"],
  ["Bushaltestelle", "die", "bus stop", "A1"],
  ["Decke", "die", "ceiling / blanket", "A1"],
  ["Dusche", "die", "shower", "A1"],
  ["Eingang", "der", "entrance", "A1"],
  ["Fahrkarte", "die", "ticket", "A1"],
  ["Fahrrad", "das", "bicycle", "A1"],
  ["Flasche", "die", "bottle", "A1"],
  ["Frühstück", "das", "breakfast", "A1"],
  ["Gabel", "die", "fork", "A1"],
  ["Geburtsort", "der", "place of birth", "A1"],
  ["Gemüse", "das", "vegetables", "A1"],
  ["Geschäft", "das", "shop / business", "A1"],
  ["Getränk", "das", "drink", "A1"],
  ["Haltestelle", "die", "stop / station", "A1"],
  ["Hemd", "das", "shirt", "A1"],
  ["Hose", "die", "trousers", "A1"],
  ["Jacke", "die", "jacket", "A1"],
  ["Kasse", "die", "checkout / cash desk", "A1"],
  ["Keller", "der", "basement", "A1"],
  ["Kleid", "das", "dress", "A1"],
  ["Küche", "die", "kitchen", "A1"],
  ["Löffel", "der", "spoon", "A1"],
  ["Messer", "das", "knife", "A1"],
  ["Miete", "die", "rent", "A1"],
  ["Obst", "das", "fruit", "A1"],
  ["Pass", "der", "passport", "A1"],
  ["Reis", "der", "rice", "A1"],
  ["Reise", "die", "journey / trip", "A1"],
  ["Saft", "der", "juice", "A1"],
  ["Schlüssel", "der", "key", "A1"],
  ["Schrank", "der", "cupboard / wardrobe", "A1"],
  ["Speisekarte", "die", "menu", "A1"],
  ["Tasse", "die", "cup", "A1"],
  ["Treppe", "die", "stairs", "A1"],
  ["Unterschrift", "die", "signature", "A1"],
  ["Wohnzimmer", "das", "living room", "A1"],
  ["Zahnbürste", "die", "toothbrush", "A1"],
  ["Ausflug", "der", "excursion", "A2"],
  ["Ausgang", "der", "exit", "A2"],
  ["Auskunft", "die", "information", "A2"],
  ["Aussicht", "die", "view / prospect", "A2"],
  ["Bewerbung", "die", "application", "A2"],
  ["Briefmarke", "die", "postage stamp", "A2"],
  ["Broschüre", "die", "brochure", "A2"],
  ["Einladung", "die", "invitation", "A2"],
  ["Eintritt", "der", "admission / entry", "A2"],
  ["Fahrplan", "der", "timetable", "A2"],
  ["Feierabend", "der", "end of the working day", "A2"],
  ["Fernbedienung", "die", "remote control", "A2"],
  ["Gehalt", "das", "salary", "A2"],
  ["Gepäck", "das", "luggage", "A2"],
  ["Gewohnheit", "die", "habit", "A2"],
  ["Haushalt", "der", "household", "A2"],
  ["Heizung", "die", "heating", "A2"],
  ["Jugendherberge", "die", "youth hostel", "A2"],
  ["Kündigung", "die", "notice / termination", "A2"],
  ["Lebenslauf", "der", "résumé / curriculum vitae", "A2"],
  ["Lebensmittel", "das", "food item", "A2"],
  ["Müll", "der", "rubbish", "A2"],
  ["Nachbarin", "die", "neighbour (f)", "A2"],
  ["Notfall", "der", "emergency", "A2"],
  ["Päckchen", "das", "small parcel", "A2"],
  ["Quittung", "die", "receipt", "A2"],
  ["Rathaus", "das", "town hall", "A2"],
  ["Rechnung", "die", "bill / invoice", "A2"],
  ["Reisepass", "der", "passport", "A2"],
  ["Sprechstunde", "die", "consultation hour", "A2"],
  ["Steckdose", "die", "electrical socket", "A2"],
  ["Teilnehmerin", "die", "participant (f)", "A2"],
  ["Verspätung", "die", "delay", "A2"],
  ["Vorname", "der", "first name", "A2"],
  ["Wörterbuch", "das", "dictionary", "A2"],
  ["Zahnpasta", "die", "toothpaste", "A2"],
  ["Flughafen", "der", "airport", "A2"],
  ["Insel", "die", "island", "A2"],
  ["Spielplatz", "der", "playground", "A2"],
  ["Schwimmbad", "das", "swimming pool", "A2"],
  ["Ladegerät", "das", "charger", "A2"],
  ["Waschbecken", "das", "washbasin", "A2"],
  ["Backofen", "der", "oven", "A2"],
  ["Wasserkocher", "der", "kettle", "A2"],
  ["Pfand", "das", "deposit", "A2"],
  ["Rückgabe", "die", "return", "A2"],
  ["Turnhalle", "die", "gymnasium / sports hall", "A2"],
  ["Schulhof", "der", "schoolyard", "A2"],
  ["Klassenraum", "der", "classroom", "A2"],
  ["Fahrstuhl", "der", "lift / elevator", "A2"],
  ["Fahrradweg", "der", "cycle path", "A2"],
  ["Kreisverkehr", "der", "roundabout", "A2"],
  ["Zebrastreifen", "der", "pedestrian crossing", "A2"],
  ["Mülltonne", "die", "rubbish bin", "A2"],
  ["Wartezimmer", "das", "waiting room", "A2"],

  // B1: independent daily, civic, educational, and working life
  ["Abteilung", "die", "department", "B1"],
  ["Anmeldung", "die", "registration", "B1"],
  ["Ansage", "die", "announcement", "B1"],
  ["Antrag", "der", "application / request", "B1"],
  ["Arbeitsplatz", "der", "workplace", "B1"],
  ["Aufenthalt", "der", "stay / residence", "B1"],
  ["Aufnahme", "die", "admission / recording", "B1"],
  ["Ausnahme", "die", "exception", "B1"],
  ["Ausstattung", "die", "equipment / furnishings", "B1"],
  ["Bedienung", "die", "service / operation", "B1"],
  ["Bedingung", "die", "condition", "B1"],
  ["Beitrag", "der", "contribution", "B1"],
  ["Beratung", "die", "advice / consultation", "B1"],
  ["Beschäftigung", "die", "employment / activity", "B1"],
  ["Beschwerde", "die", "complaint", "B1"],
  ["Bescheid", "der", "official notice", "B1"],
  ["Bestätigung", "die", "confirmation", "B1"],
  ["Bevölkerung", "die", "population", "B1"],
  ["Beziehung", "die", "relationship", "B1"],
  ["Bildschirm", "der", "screen", "B1"],
  ["Botschaft", "die", "message / embassy", "B1"],
  ["Brand", "der", "fire / blaze", "B1"],
  ["Dauer", "die", "duration", "B1"],
  ["Eigenschaft", "die", "characteristic", "B1"],
  ["Einigung", "die", "agreement", "B1"],
  ["Einsatz", "der", "deployment / use", "B1"],
  ["Empfang", "der", "reception", "B1"],
  ["Empfehlung", "die", "recommendation", "B1"],
  ["Entfernung", "die", "distance", "B1"],
  ["Erlaubnis", "die", "permission", "B1"],
  ["Ermäßigung", "die", "discount", "B1"],
  ["Ernährung", "die", "nutrition", "B1"],
  ["Fähigkeit", "die", "ability", "B1"],
  ["Fahrbahn", "die", "roadway", "B1"],
  ["Fortbildung", "die", "professional development", "B1"],
  ["Fortschritt", "der", "progress", "B1"],
  ["Freiwillige", "die", "volunteer (f)", "B1"],
  ["Führerschein", "der", "driving licence", "B1"],
  ["Gemeinschaft", "die", "community", "B1"],
  ["Genehmigung", "die", "approval / permit", "B1"],
  ["Gesundheitssystem", "das", "healthcare system", "B1"],
  ["Gewinn", "der", "profit / gain", "B1"],
  ["Grundstück", "das", "plot of land", "B1"],
  ["Herkunft", "die", "origin", "B1"],
  ["Hinweis", "der", "notice / indication", "B1"],
  ["Hochzeit", "die", "wedding", "B1"],
  ["Kenntnis", "die", "knowledge", "B1"],
  ["Kraftstoff", "der", "fuel", "B1"],
  ["Kreuzung", "die", "intersection", "B1"],
  ["Lieferung", "die", "delivery", "B1"],
  ["Mahlzeit", "die", "meal", "B1"],
  ["Mehrheit", "die", "majority", "B1"],
  ["Mitteilung", "die", "notification / message", "B1"],
  ["Nachteil", "der", "disadvantage", "B1"],
  ["Nachwuchs", "der", "young talent / offspring", "B1"],
  ["Öffentlichkeit", "die", "public", "B1"],
  ["Pflege", "die", "care", "B1"],
  ["Pflicht", "die", "duty", "B1"],
  ["Ratschlag", "der", "advice", "B1"],
  ["Rückfahrt", "die", "return journey", "B1"],
  ["Rücksicht", "die", "consideration", "B1"],
  ["Schaden", "der", "damage", "B1"],
  ["Schalter", "der", "counter / switch", "B1"],
  ["Schicht", "die", "shift / layer", "B1"],
  ["Schutz", "der", "protection", "B1"],
  ["Schwerpunkt", "der", "focus", "B1"],
  ["Sicherheit", "die", "safety / security", "B1"],
  ["Störung", "die", "disruption / fault", "B1"],
  ["Teilnahme", "die", "participation", "B1"],
  ["Umgebung", "die", "surroundings", "B1"],
  ["Umleitung", "die", "diversion", "B1"],
  ["Umzug", "der", "move / parade", "B1"],
  ["Unterkunft", "die", "accommodation", "B1"],
  ["Unterschied", "der", "difference", "B1"],
  ["Veranstaltung", "die", "event", "B1"],
  ["Verbrauch", "der", "consumption", "B1"],
  ["Vereinbarung", "die", "agreement", "B1"],
  ["Verhalten", "das", "behaviour", "B1"],
  ["Verletzung", "die", "injury", "B1"],
  ["Vermieterin", "die", "landlord (f)", "B1"],
  ["Voraussetzung", "die", "requirement / prerequisite", "B1"],
  ["Vorschrift", "die", "regulation", "B1"],
  ["Wahrheit", "die", "truth", "B1"],
  ["Werkzeug", "das", "tool", "B1"],
  ["Wirkung", "die", "effect", "B1"],
  ["Zusammenhang", "der", "connection / context", "B1"],
  ["Zustand", "der", "condition / state", "B1"],
  ["Zustimmung", "die", "consent / approval", "B1"],

  // B2: public life, work, culture, science, and abstract discussion
  ["Abhängigkeit", "die", "dependence", "B2"],
  ["Absicht", "die", "intention", "B2"],
  ["Abstimmung", "die", "vote / coordination", "B2"],
  ["Anerkennung", "die", "recognition", "B2"],
  ["Anforderung", "die", "requirement", "B2"],
  ["Angelegenheit", "die", "matter / affair", "B2"],
  ["Annahme", "die", "assumption / acceptance", "B2"],
  ["Anspruch", "der", "claim / entitlement", "B2"],
  ["Anteil", "der", "share / proportion", "B2"],
  ["Arbeitskraft", "die", "worker / labour capacity", "B2"],
  ["Auseinandersetzung", "die", "dispute / engagement", "B2"],
  ["Auswirkung", "die", "impact", "B2"],
  ["Bedarf", "der", "need / demand", "B2"],
  ["Befragung", "die", "survey / questioning", "B2"],
  ["Befugnis", "die", "authority / power", "B2"],
  ["Begründung", "die", "justification", "B2"],
  ["Belastung", "die", "burden / strain", "B2"],
  ["Bereitschaft", "die", "willingness / readiness", "B2"],
  ["Beschluss", "der", "decision / resolution", "B2"],
  ["Bestand", "der", "stock / continued existence", "B2"],
  ["Bestimmung", "die", "provision / purpose", "B2"],
  ["Beteiligung", "die", "participation / stake", "B2"],
  ["Bewertung", "die", "evaluation", "B2"],
  ["Bewusstsein", "das", "awareness / consciousness", "B2"],
  ["Darstellung", "die", "representation / presentation", "B2"],
  ["Datenschutz", "der", "data protection", "B2"],
  ["Einschätzung", "die", "assessment", "B2"],
  ["Einschränkung", "die", "restriction", "B2"],
  ["Entschädigung", "die", "compensation", "B2"],
  ["Entwicklungshilfe", "die", "development aid", "B2"],
  ["Erhebung", "die", "survey / collection", "B2"],
  ["Erkenntnis", "die", "insight / finding", "B2"],
  ["Erscheinung", "die", "appearance / phenomenon", "B2"],
  ["Erwartung", "die", "expectation", "B2"],
  ["Fachkraft", "die", "skilled worker", "B2"],
  ["Fassung", "die", "version / composure", "B2"],
  ["Förderung", "die", "support / funding", "B2"],
  ["Forschungsergebnis", "das", "research finding", "B2"],
  ["Fragestellung", "die", "research question / issue", "B2"],
  ["Gegensatz", "der", "contrast / opposite", "B2"],
  ["Gegenstand", "der", "object / subject", "B2"],
  ["Gerechtigkeit", "die", "justice", "B2"],
  ["Gesetzgebung", "die", "legislation", "B2"],
  ["Gestaltung", "die", "design / shaping", "B2"],
  ["Glaubwürdigkeit", "die", "credibility", "B2"],
  ["Gleichberechtigung", "die", "equal rights", "B2"],
  ["Haltung", "die", "attitude / posture", "B2"],
  ["Handlung", "die", "action / plot", "B2"],
  ["Herausforderung", "die", "challenge", "B2"],
  ["Herstellung", "die", "production", "B2"],
  ["Identität", "die", "identity", "B2"],
  ["Infrastruktur", "die", "infrastructure", "B2"],
  ["Klimawandel", "der", "climate change", "B2"],
  ["Lebensqualität", "die", "quality of life", "B2"],
  ["Leistungskraft", "die", "capacity / efficiency", "B2"],
  ["Maßstab", "der", "standard / scale", "B2"],
  ["Maßnahme", "die", "measure / action", "B2"],
  ["Mangel", "der", "shortage / defect", "B2"],
  ["Nachhaltigkeit", "die", "sustainability", "B2"],
  ["Nachweis", "der", "proof / evidence", "B2"],
  ["Niederlassung", "die", "branch / settlement", "B2"],
  ["Nutzung", "die", "use / utilisation", "B2"],
  ["Rahmenbedingung", "die", "framework condition", "B2"],
  ["Reichweite", "die", "reach / range", "B2"],
  ["Richtlinie", "die", "guideline / directive", "B2"],
  ["Sachverhalt", "der", "facts / circumstances", "B2"],
  ["Selbstständigkeit", "die", "independence / self-employment", "B2"],
  ["Stellungnahme", "die", "statement / opinion", "B2"],
  ["Steuerung", "die", "control / management", "B2"],
  ["Tatsache", "die", "fact", "B2"],
  ["Tragweite", "die", "implications / scope", "B2"],
  ["Übereinstimmung", "die", "agreement / correspondence", "B2"],
  ["Umsetzung", "die", "implementation", "B2"],
  ["Ungleichheit", "die", "inequality", "B2"],
  ["Verfügbarkeit", "die", "availability", "B2"],
  ["Verbindlichkeit", "die", "binding nature / reliability", "B2"],
  ["Verbreitung", "die", "spread / distribution", "B2"],
  ["Verdacht", "der", "suspicion", "B2"],
  ["Verfahren", "das", "procedure / process", "B2"],
  ["Verhältnis", "das", "relationship / ratio", "B2"],
  ["Vermögen", "das", "assets / ability", "B2"],
  ["Versorgung", "die", "supply / care", "B2"],
  ["Verständnis", "das", "understanding", "B2"],
  ["Verteilung", "die", "distribution", "B2"],
  ["Vorgehen", "das", "approach / procedure", "B2"],
  ["Wahrnehmung", "die", "perception", "B2"],
  ["Wettbewerbsfähigkeit", "die", "competitiveness", "B2"],
  ["Widerspruch", "der", "contradiction / objection", "B2"],
  ["Zielsetzung", "die", "objective", "B2"],
  ["Zugangsvoraussetzung", "die", "admission requirement", "B2"],
  ["Zuverlässigkeit", "die", "reliability", "B2"],
  ["Abbau", "der", "reduction / dismantling", "B2"],
  ["Ablauf", "der", "process / sequence", "B2"],
  ["Absicherung", "die", "protection / safeguarding", "B2"],
  ["Ausschuss", "der", "committee", "B2"],
  ["Auswertung", "die", "evaluation / analysis", "B2"],
  ["Bedenken", "das", "concern / reservation", "B2"],
  ["Befürchtung", "die", "fear / concern", "B2"],
  ["Beleg", "der", "evidence / receipt", "B2"],
  ["Bemühung", "die", "effort", "B2"],
  ["Bereich", "der", "area / field", "B2"],
  ["Berücksichtigung", "die", "consideration", "B2"],
  ["Beschaffung", "die", "procurement", "B2"],
  ["Datenerhebung", "die", "data collection", "B2"],
  ["Einbeziehung", "die", "inclusion", "B2"],
  ["Einflussnahme", "die", "exertion of influence", "B2"],
  ["Einhaltung", "die", "compliance", "B2"],
  ["Einrichtung", "die", "institution / facility", "B2"],
  ["Einwanderung", "die", "immigration", "B2"],
  ["Emissionsminderung", "die", "emissions reduction", "B2"],
  ["Entlastung", "die", "relief / easing", "B2"],
  ["Erfordernis", "das", "requirement / necessity", "B2"],
  ["Erhaltung", "die", "preservation", "B2"],
  ["Finanzierung", "die", "financing", "B2"],
  ["Freiheitsrecht", "das", "civil liberty", "B2"],
  ["Gegenleistung", "die", "consideration / return service", "B2"],
  ["Gegenwart", "die", "present", "B2"],
  ["Gesamtbetrag", "der", "total amount", "B2"],
  ["Gesichtspunkt", "der", "aspect / point of view", "B2"],
  ["Grundsatz", "der", "principle", "B2"],
  ["Haftung", "die", "liability", "B2"],
  ["Hemmschwelle", "die", "inhibition threshold", "B2"],
  ["Kaufkraft", "die", "purchasing power", "B2"],
  ["Kernaufgabe", "die", "core task", "B2"],
  ["Lernfortschritt", "der", "learning progress", "B2"],
  ["Meinungsfreiheit", "die", "freedom of expression", "B2"],
  ["Mietverhältnis", "das", "tenancy", "B2"],
  ["Mittelwert", "der", "mean value", "B2"],
  ["Nebenwirkung", "die", "side effect", "B2"],
  ["Neigung", "die", "inclination / tendency", "B2"],
  ["Nutzungsdauer", "die", "service life", "B2"],
  ["Rechtsanspruch", "der", "legal entitlement", "B2"],
  ["Rechtslage", "die", "legal situation", "B2"],
  ["Rückgang", "der", "decline", "B2"],
  ["Schätzung", "die", "estimate", "B2"],
  ["Selbsteinschätzung", "die", "self-assessment", "B2"],
  ["Sprachkenntnis", "die", "language proficiency", "B2"],
  ["Steuereinnahme", "die", "tax revenue", "B2"],
  ["Übertragung", "die", "transmission / transfer", "B2"],
  ["Verhandlungsbasis", "die", "basis for negotiation", "B2"],
  ["Vermittlung", "die", "mediation / placement", "B2"],
  ["Verpflichtung", "die", "obligation", "B2"],
  ["Vertretung", "die", "representation / substitute", "B2"],
  ["Vorkehrung", "die", "precaution", "B2"],
  ["Vorrang", "der", "priority", "B2"],
  ["Wertschätzung", "die", "appreciation", "B2"],
  ["Zahlungsfrist", "die", "payment deadline", "B2"],
  ["Zuwanderung", "die", "immigration", "B2"],

  // C1: precise academic, institutional, and professional vocabulary
  ["Abgrenzung", "die", "distinction / demarcation", "C1"],
  ["Abwägung", "die", "weighing of interests", "C1"],
  ["Anreiz", "der", "incentive", "C1"],
  ["Auslegung", "die", "interpretation", "C1"],
  ["Beeinträchtigung", "die", "impairment", "C1"],
  ["Befund", "der", "finding / diagnosis", "C1"],
  ["Beschaffenheit", "die", "nature / composition", "C1"],
  ["Daseinsvorsorge", "die", "public services", "C1"],
  ["Eigenverantwortung", "die", "personal responsibility", "C1"],
  ["Einwand", "der", "objection", "C1"],
  ["Folgerung", "die", "conclusion / inference", "C1"],
  ["Gebietskörperschaft", "die", "territorial authority", "C1"],
  ["Geltungsbereich", "der", "scope of application", "C1"],
  ["Gewährleistung", "die", "guarantee / warranty", "C1"],
  ["Handlungsspielraum", "der", "room for manoeuvre", "C1"],
  ["Herangehensweise", "die", "approach", "C1"],
  ["Leistungsfähigkeit", "die", "performance capacity", "C1"],
  ["Nachvollziehbarkeit", "die", "traceability / comprehensibility", "C1"],
  ["Rahmenregelung", "die", "framework regulation", "C1"],
  ["Rechenschaft", "die", "accountability", "C1"],
  ["Rechtsgrundlage", "die", "legal basis", "C1"],
  ["Schlussfolgerung", "die", "conclusion", "C1"],
  ["Schwellenwert", "der", "threshold", "C1"],
  ["Stellenwert", "der", "importance / status", "C1"],
  ["Tatbestand", "der", "facts constituting an offence", "C1"],
  ["Wechselwirkung", "die", "interaction", "C1"],
  ["Zweckmäßigkeit", "die", "expediency / practicality", "C1"],
  ["Abhilfemaßnahme", "die", "remedial measure", "C1"],
  ["Abschreckung", "die", "deterrence", "C1"],
  ["Anhaltspunkt", "der", "indication / clue", "C1"],
  ["Anwendbarkeit", "die", "applicability", "C1"],
  ["Ausgestaltung", "die", "detailed design", "C1"],
  ["Ausnahmeregelung", "die", "exemption provision", "C1"],
  ["Beweislast", "die", "burden of proof", "C1"],
  ["Datenbestand", "der", "data set / data holdings", "C1"],
  ["Durchsetzbarkeit", "die", "enforceability", "C1"],
  ["Eingriff", "der", "intervention / encroachment", "C1"],
  ["Einzelfall", "der", "individual case", "C1"],
  ["Ermessensspielraum", "der", "discretion", "C1"],
  ["Folgewirkung", "die", "secondary effect", "C1"],
  ["Gesamtschau", "die", "overall assessment", "C1"],
  ["Grundannahme", "die", "basic assumption", "C1"],
  ["Interessenausgleich", "der", "balance of interests", "C1"],
  ["Kausalzusammenhang", "der", "causal connection", "C1"],
  ["Kenngröße", "die", "key figure / parameter", "C1"],
  ["Kohärenz", "die", "coherence", "C1"],
  ["Leitgedanke", "der", "guiding principle", "C1"],
  ["Machtbefugnis", "die", "authority / power", "C1"],
  ["Nachbesserung", "die", "rectification / improvement", "C1"],
  ["Nachweispflicht", "die", "obligation to provide evidence", "C1"],
  ["Plausibilität", "die", "plausibility", "C1"],
  ["Rechtfertigung", "die", "justification", "C1"],
  ["Rechtsbehelf", "der", "legal remedy", "C1"],
  ["Rechtsfolge", "die", "legal consequence", "C1"],
  ["Regelungsbedarf", "der", "need for regulation", "C1"],
  ["Risikobewertung", "die", "risk assessment", "C1"],
  ["Sachgebiet", "das", "subject area", "C1"],
  ["Schadensersatz", "der", "damages / compensation", "C1"],
  ["Schutzwürdigkeit", "die", "worthiness of protection", "C1"],
  ["Selbstbestimmung", "die", "self-determination", "C1"],
  ["Sorgfaltspflicht", "die", "duty of care", "C1"],
  ["Stichhaltigkeit", "die", "validity / cogency", "C1"],
  ["Trennschärfe", "die", "distinctness", "C1"],
  ["Überprüfbarkeit", "die", "verifiability", "C1"],
  ["Unbedenklichkeit", "die", "safety / harmlessness", "C1"],
  ["Verhältnismäßigkeit", "die", "proportionality", "C1"],
  ["Verursacherprinzip", "das", "polluter-pays principle", "C1"],
  ["Vollziehbarkeit", "die", "executability", "C1"],
  ["Vorhersehbarkeit", "die", "foreseeability", "C1"],
  ["Wirkungsgrad", "der", "efficiency", "C1"],
  ["Zumutbarkeit", "die", "reasonableness", "C1"],
  ["Zurechenbarkeit", "die", "attributability", "C1"],
  ["Zweckbindung", "die", "purpose limitation", "C1"],
];

const SOURCE = "Goethe vocabulary framework cross-check; German corpus frequency tranche; case content review pending";

export const VERSION_FOUR_NOUNS = RAW_NOUNS.map(([noun, gender, en, cefr], index) => ({
  seedVersion: 4,
  noun,
  gender,
  en,
  cefr,
  frequencyRank: 1169 + index,
  sourceVerification: SOURCE,
  casePracticeStatus: "pending",
}));
